fund_frontier/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('npv.urls')),
    
]

npv/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.base, name='base'),  # URL for the home page
    path('contact/', views.contact, name='contact'),  # URL for the contact page
    path('create_evaluation/', views.create_evaluation, name='create_evaluation'),  # URL for the NPV calculation form
    path('edit_evaluation/<str:evaluation_id>/', views.edit_evaluation, name='edit_evaluation'),
    path('delete_evaluation/<str:evaluation_id>/', views.delete_evaluation, name='delete_evaluation'),
    path('add_project/<int:evaluation_id>/', views.add_project, name='add_project'),  # URL for the NPV calculation form
    path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),  # URL for the NPV calculation form
    path('edit_project/<int:project_id>/', views.edit_project, name='edit_project'),  # URL for the NPV calculation form
    path('list-evaluations/', views.list_evaluations, name='list-evaluations'),  # URL for listing evaluations
    path('list-evaluation-projects/<int:evaluation_id>/', views.list_evaluation_projects, name='list-evaluation-projects'),  # URL for listing evaluations
]

npv/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator


class Evaluation(models.Model):
    """
    Model representing an evaluation with a name and discount rate.
    """
    name = models.CharField(max_length=255)
    discount_rate = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(0), MaxValueValidator(1)])  # store as decimal between 0 and 1 which i a %
    note = models.CharField(max_length=200, null=True, blank=True)
    number_of_projects = models.IntegerField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Project(models.Model):
    """
    Model representing a project with various financial metrics and calculations.
    """
    CONSIDER_FURTHER_CHOICES = [
        ('yes', 'Yes'),
        ('rejected', 'Rejected'),
    ]

    evaluation = models.ForeignKey(Evaluation, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    initial_investment = models.DecimalField(max_digits=10, decimal_places=2)  # store as decimal
    cash_flow_year_1 = models.DecimalField(max_digits=10, decimal_places=2, null=True)  # store as decimal
    period = models.IntegerField()

    # Fields to store calculated values
    npv = models.FloatField(
        null=True, blank=True)
    payback_period = models.IntegerField(null=True, blank=True)
    annualized_npv = models.FloatField(null=True, blank=True)

    # New field to indicate whether to consider further or reject
    consider_further = models.CharField(
        max_length=10, choices=CONSIDER_FURTHER_CHOICES, default='yes')

    # New field for ranking
    rank = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name

    def calculate_npv(self, cash_flows_input):
        if not isinstance(cash_flows_input, list):
            raise ValueError("cash_flows_input must be a list")
        cash_flows = [-self.initial_investment] + cash_flows_input
        npv_value = sum(cash_flow / ((1 + float(self.evaluation.discount_rate)) ** t) for t, cash_flow in enumerate(cash_flows))
        self.npv = round(npv_value, 2)
        if self.npv < 0:
            self.consider_further = 'rejected'
        else:
            self.consider_further = 'accepted'
        self.save()
        return self.npv


    def calculate_payback_period(self, cash_flows_input):
        """
        Calculate Payback Period for the project.
        """
        cumulative_cash_flow = -self.initial_investment
        for year, cash_flow in enumerate(cash_flows_input, start=1):
            cumulative_cash_flow += cash_flow
            if cumulative_cash_flow >= 0:
                self.payback_period = year
                return self.payback_period
        return None


    def calculate_annualized_npv(self):
        """
        Calculate Equivalent Annual Annuity (EAA) for the project if the periods are different.
        """
        try:
            npv_value = self.npv
            discount_rate = float(self.evaluation.discount_rate)
            annualized_npv = npv_value * discount_rate / (1 - (1 + discount_rate) ** -self.period)
            self.annualized_npv = round(annualized_npv, 2)
            return self.annualized_npv
        except Exception as e:
            print(f"Error calculating annualized NPV: {e}")
            return None
        
        
    def save(self, *args, **kwargs):
        """
        Override the save method to update the rank before saving the project.
        """
        self.calculate_annualized_npv()
        super().save(*args, **kwargs)

class CashFlow(models.Model):
    """
    Model representing a cash flow for a specific year of a project.
    """
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    year = models.IntegerField()
    amount = models.FloatField()

    def __str__(self):
        return f'Year {self.year}: {self.amount}'

npv/forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator

class Evaluation_Form(forms.Form):
    evaluation_name = forms.CharField(label="Evaluation Name")
    discount_rate = forms.FloatField(label="Discount Rate(%)", widget=forms.NumberInput(attrs={'type': 'number', 'step': '0.01', 'class': 'percentage'}), validators=[MaxValueValidator(100), MinValueValidator(0)])
    note = forms.CharField(label="Note(optional)", required=False)


class Project_Form(forms.Form):
    initial_investment = forms.FloatField(label="Initial investment", widget=forms.NumberInput(attrs={'type': 'number', 'class': 'currency'}))
    project_name = forms.CharField(label="Project Name")
    cash_flow_year_1 = forms.FloatField(label = "Cash flow year 1 $", widget=forms.NumberInput(attrs={'type': 'number', 'class': 'currency'}))
    cash_flow_year_count = forms.FloatField(widget=forms.HiddenInput())

    
    def __init__(self, *args, **kwargs):
        # set extra to zero this is then passed to the view when you're collecting the form data
        # e.g. form = Project_Form(request.POST, extra=request.POST.get('cash_flow_year_count', 0))
        extra_fields = kwargs.pop('extra', 0)

        # when the form is initialized set the count to 1
        super(Project_Form, self).__init__(*args, **kwargs)
        self.fields['cash_flow_year_count'].initial = 1

        # For all of the extra fields
        for index in range(2, int(extra_fields) + 1):

            # Make sure the newly added cash flows are floats
            self.fields[f'cash_flow_year_{index}'] = forms.FloatField()

class ContactForm(forms.Form):
    # Define your form fields here
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

npv/views.py
import json
from django.shortcuts import render, get_object_or_404
from .models import Evaluation, Project, CashFlow
from .forms import Project_Form, Evaluation_Form, ContactForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse


def base(request):
    context = {'some_key': 'some_value'}  # Replace with actual context data
    return render(request, 'npv/about.html', context)



def contact(request):
    context = {'some_key': 'some_value'}
    return render(request, 'npv/contact.html', context)

@login_required
def create_evaluation(request):
    if request.method == "POST":
        # get data from form
        form = Evaluation_Form(request.POST)
        if form.is_valid():
            # Create list for cash flows
            cash_flows = []

            # Save discount rate
            discount_rate = float(form.cleaned_data["discount_rate"]) / 100

            # Create a new evaluation
            evaluation = Evaluation.objects.create(
                name=form.cleaned_data["evaluation_name"],
                discount_rate=discount_rate,
                note=form.cleaned_data["note"],
                user = request.user
            )
            evaluation.save()

            form=Project_Form()

            # Send an empty project form and the evaluation id to the add project page
            return render(request, "npv/add-project.html", {"form": form, "evaluation_id": evaluation.id}) 

    # first coming to the page (with a GET request) display an empty evaluation form
    form = Evaluation_Form()       
    return render(request, "npv/create-evaluation.html", {"form": form})

@login_required
def add_project(request, evaluation_id):
    if request.method == "POST":
        # get project data from the form
        form = Project_Form(request.POST, extra=request.POST.get(
            'cash_flow_year_count', 0))
        if form.is_valid():

            # Create list for cash flows
            cash_flows = []

            # Loop through each cash flow and add to cash flow list
            cash_flow_year_count = form.cleaned_data.get("cash_flow_year_count")
            if cash_flow_year_count is not None:
                for i in range(1, int(cash_flow_year_count) + 1):
                    cash_flow_key = "cash_flow_year_" + str(i)
                    if cash_flow_key in form.cleaned_data:
                        cash_flows.append(form.cleaned_data[cash_flow_key])

            evaluation = Evaluation.objects.get(id=evaluation_id)

            # Create a new project
            project = Project.objects.create(
                evaluation=evaluation,
                name=form.cleaned_data["project_name"],
                initial_investment=float(form.cleaned_data["initial_investment"]),
                period=len(cash_flows)
            )

            # Call the calculate_npv and calculate_payback_period method 
            # in the model using the projects cash flows
            project.calculate_npv(cash_flows)
            project.calculate_payback_period(cash_flows)
            project.save()
            
            # Create CashFlow rows for each cash flow for the project
            for i, cash_flow in enumerate(cash_flows, start=1):
                CashFlow.objects.create(
                    project=project,
                    year=i,
                    amount=float(cash_flow),
                )
                
            # If the user uses the complete evaluation button
            if 'complete_eval' in request.POST:
                # Rank the projects
                projects_same_evaluation = Project.objects.filter(evaluation=evaluation).order_by('npv').values_list('id', flat=True)

                for rank, project_id in enumerate(projects_same_evaluation):
                    project_by_id = Project.objects.get(id=project_id)
                    setattr(project_by_id, 'rank', rank+1)
                    project_by_id.save()

                # And add the number of projects to the evaluation
                evaluation.number_of_projects = len(projects_same_evaluation)
                evaluation.save()
                
                # call the list_evaluation_projects so the user views the list of projects for the eval
                return list_evaluation_projects(request, evaluation_id)

            # Otherwise move on to the next empty for for the project
            form = Project_Form()

            return render(request, "npv/add-project.html", {"form": form, "evaluation_id": evaluation.id}) 

    # display an empty page when you call this page (I dont think is actually ever hit 
    # unless the user goes directly to the url)
    form = Project_Form()       
    return render(request, "npv/add-project.html", {"form": form, "evaluation_id": evaluation_id})
            

@login_required
def list_evaluations(request):
    evaluations = Evaluation.objects.all().order_by('-id')
    return render(request, "npv/list-evaluations.html", {"evaluations": evaluations})


@login_required
def list_evaluation_projects(request, evaluation_id):
    evaluation = Evaluation.objects.get(id=evaluation_id)

    projects = Project.objects.filter(evaluation=evaluation).order_by('rank')
    return render(request, "npv/list-projects.html", {"projects": projects, "evaluation_name": evaluation.name})


@login_required
def edit_evaluation(request, evaluation_id):
    evaluation = Evaluation.objects.get(id=evaluation_id)
    if request.method == "POST":
        # get the updated data for the evaluation
        form = Evaluation_Form(request.POST)
        if form.is_valid():
            # Create list for cash flows
            cash_flows = []

             # Save discount rate
            discount_rate = float(form.cleaned_data["discount_rate"]) / 100

             # Update info of the evaluation
            evaluation.name = form.cleaned_data["evaluation_name"]
            evaluation.discount_rate = discount_rate
            evaluation.note = form.cleaned_data["note"]
            evaluation.user = request.user
            evaluation.save()
            
            

        # go back to list of evaluations
        evaluations = Evaluation.objects.all().order_by('-id')
        return render(request, "npv/list-evaluations.html", {"evaluations": evaluations})

    # grab the data
    data = {
            'discount_rate': evaluation.discount_rate,
            'evaluation_name': evaluation.name, 
            'note': evaluation.note}
    
    # Populate the form with that data
    form = Evaluation_Form(initial=data)

    return render(request, "npv/edit-eval.html", {"form": form, "evaluation_id":evaluation_id, "eval_name": evaluation.name})


@login_required
def edit_project(request, project_id):
    if request.method == "POST":
        # get the updated data of the project
        form = Project_Form(request.POST, extra=request.POST.get(
            'cash_flow_year_count', 0))
        if form.is_valid():
            # Create list for cash flows
            cash_flows = []

            # Loop through each cash flow and add to cash flow list
            cash_flow_year_count = form.cleaned_data.get("cash_flow_year_count")
            if cash_flow_year_count is not None:
                for i in range(1, int(cash_flow_year_count) + 1):
                    cash_flow_key = "cash_flow_year_" + str(i)
                    if cash_flow_key in form.cleaned_data:
                        cash_flows.append(form.cleaned_data[cash_flow_key])

            # Update the data and save the project
            project = Project.objects.get(id=project_id)
            project.name=form.cleaned_data["project_name"]
            project.initial_investment=form.cleaned_data["initial_investment"]
            project.period=len(cash_flows)
            project.calculate_npv(cash_flows)
            project.calculate_payback_period(cash_flows)
            project.save()
            
            # Loop through cash flows and update amounts
            # TODO: is the year right here? Too tired right now ....
            for i, cash_flow in enumerate(cash_flows, start=1):
                # if the cashflow already existed update it
                try:
                    cash_flow_instance = CashFlow.objects.get(project=project,
                                                         year=i)
                # otherwise create a new one
                except:
                    cash_flow_instance = CashFlow.objects.create(
                    project=project,
                    year=i,
                    amount=cash_flow,
                )
                cash_flow_instance.save()
                
            # Preform the ranking again with the projects
            projects_same_evaluation = Project.objects.filter(evaluation=project.evaluation).order_by('npv').values_list('id', flat=True)
            for rank, project_id in enumerate(projects_same_evaluation):
                project_by_id = Project.objects.get(id=project_id)
                setattr(project_by_id, 'rank', rank+1)
                project_by_id.save()
                
            return list_evaluation_projects(request, project.evaluation.id)

    # When first coming to the edit page get the data for the project you want to edit
    project = Project.objects.get(id=project_id)

    # This is used to send the cash flows (except the first one) to the JavaScript on edit-project.html
    cash_flows_dict = {}
    # form data
    data = {}
    # all cash flows relaated to the project
    cash_flows = CashFlow.objects.filter(project=project)
    for cash_flow in cash_flows:
        # This may not actuall be neccesary but collect them all for the form
        data["cash_flow_year_" + str(cash_flow.year)] = cash_flow.amount
        # Add them to the dict that we're sending to the JS on the edit-project.html page
        cash_flows_dict[str(cash_flow.year)] = float(cash_flow.amount)

templates/npv/about.html
{% extends 'base.html' %}


{% load static %}
{% block extra_meta %}
<!-- Specific meta tags for the About page can be placed here -->
{% endblock %}
{% block extra_css %}

{% endblock %}
{% block extra_title %}About Fund Frontier{% endblock %}
{% block content %}
<div class="about-page text-white mt-5">
    <section class="intro-container animated slideInFromRight">
        <h1>About Fund Frontier</h1>
        <p>Empowering your investment decisions with precision and insight.</p>
    </section>
    <!-- Introduction and Purpose -->
    <section class="intro-container animated slideInFromLeft">
        <h2>Empowering Investment Decisions</h2>
        <p>
            Fund Frontier is at the forefront of investment analysis tools, offering a state-of-the-art NPV Calculator designed to empower users in making informed investment decisions. Our platform stands out by providing detailed, comprehensive analyses, enabling a thorough understanding of investment potentials and risks.
        </p>
    </section>
    <!-- Additional Section -->
    <section class="intro-container animated slideInFromRight">
        <h2>Innovative Analysis Tools</h2>
        <p>
            Explore new horizons in investment with Fund Frontier's innovative suite of analytical tools. Uncover the hidden value in your portfolio with our expert insights and user-friendly interface.
        </p>
    </section>
    <!-- Introduction and Purpose -->
    <section class="intro-container animated slideInFromLeft">
        <h2>Empowering Investment Decisions</h2>
        <p>
            Fund Frontier is at the forefront of investment analysis tools, offering a state-of-the-art NPV Calculator designed to empower users in making informed investment decisions. Our platform stands out by providing detailed, comprehensive analyses, enabling a thorough understanding of investment potentials and risks.
        </p>
    </section>

    <!-- Features and Advantages -->
    <section class="feature-section mt-5">
        <h1>Features and Advantages</h1>
        <!-- Feature 1 -->
        <div class="feature-box">
            <h3>Triple-Project Evaluation</h3>
            <p>
                Unlike most tools, Fund Frontier enables the simultaneous evaluation of up to three projects, providing a broad perspective and a meticulous comparative analysis.
            </p>
        </div>
        <!-- Feature 2 -->
        <div class="feature-box">
            <h3>Detailed Metrics</h3>
            <p>
                Our tool goes beyond mere calculations; it interprets data. With metrics like NPV and Payback Period, you're not just viewing numbers but understanding the story they tell.
            </p>
        </div>
        <!-- Feature 3 -->
        <div class="feature-box">
            <h3>User-Centric Design</h3>
            <p>
                Our platform ensures that whether you're a novice investor or a seasoned financial expert, evaluating projects is straightforward and hassle-free.
            </p>
        </div>
        <!-- Feature 4 -->
        <div class="feature-box">
            <h3>Dynamic Project Management</h3>
            <p>
                The ability to save, view, modify, and delete projects empowers you with full control over your investment analysis process.
            </p>
        </div>
        <!-- Feature 5 -->
        <div class="feature-box">
            <h3>Intelligent Project Ranking</h3>
            <p>
                Navigate investment choices with confidence. Our intelligent ranking system highlights the most lucrative projects, helping you make informed decisions swiftly.
            </p>
        </div>
        <!-- Feature 6 -->
        <div class="feature-box">
            <h3>Technological Excellence</h3>
            <p>
                Built on a foundation of robust technologies like Django and Python, Fund Frontier guarantees performance, security, and reliability.
            </p>
        </div>
    </section>
</div>
{% endblock %}
{% block extra_js %}
<!-- Specific JavaScript for the About page can be placed here -->
{% endblock %}

templates/npv/add-project.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<h3 class="calculator-headings">Add Project</h3>
<div class="site-container calculator-container col-md-6">

            {% comment %} TODO: Limit discount rate {% endcomment %}
            
    <form class="site-form" action="{% url 'add_project' evaluation_id=evaluation_id %}" method="post">
        
        <h4>Project Details</h3>
        {% csrf_token %}
        <div id="forms">
            {{ form.as_p }}
        </div>
        <button class="year" type="button" id="add-another">Add Year</button>
        <button class="year" type="button" id="delete-another">Delete Year</button>
        <button type="submit" name="add_next_project">Add Next Project</button>
        <button type="submit" name="complete_eval">Complete Evaluation</button>
    </form>
   
    </div>
</div>
{% block extra_js_footer %}
<script>
    let form_count = Number($("[name=cash_flow_year_count]").val());
    // get extra form count so we know what index to use for the next item.

    // When the add button is clicked
    $("#add-another").click(function () {
        // Add one to the count
        form_count++;
        // create the input element
        let element1 = $('<label>Cash flow year ' + form_count + ' ($)</label>');
        $("#forms").append(element1);
        // create the input element
        let element = $('<input type="number"/>');
        // Add the name so you know which value belongs to which year
        element.attr('name', 'cash_flow_year_' + form_count);
        element.attr('label', 'Cash flow year ' + form_count + ' ($)');
        // Add that field to the form
        $("#forms").append(element);
        // add the count back to the form so it can be grabbed on the next click
        $("[name=cash_flow_year_count]").val(form_count);
    })
    // When the delete button is clicked
    $("#delete-another").click(function() {
        // remove the last added input
        $('#forms input:last').remove();
        $("#forms label:last").remove();
        // reduce the count
        form_count --;
        // add the count back to the form so it can be grabbed on the next click
        $("[name=cash_flow_year_count]").val(form_count);
    })
</script>
{% endblock %}
{% endblock %}

templates/npv/contact.html
{% extends 'base.html' %}

{% load static %}

{% block extra_title %}Contact Us | Fund Frontier{% endblock %}
{% block content %}
    <div class="team-area">
            <h1>Meet the team</h1>
        <div class="team-box">
            <div class="box">
                <img src="{% static 'images/nate.png' %}" alt="team member">
                <h2>Nate</h2>
                <p>Backend</p>
                <p>
                    <a href="https://www.linkedin.com/in/redsskull/" target="_blank">
                        <i class="fa fa-linkedin fa-2x"></i>
                    </a>
                </p>
            </div>
            <div class="box">
                <img src="{% static 'images/sean.png' %}" alt="team member">
                <h2>Sean</h2>
                <p>Backend</p>
                <p>
                    <a href="https://www.linkedin.com/in/seanmeadedev/" target="_blank">
                        <i class="fa fa-linkedin fa-2x"></i>
                    </a>
                </p>
            </div>
            <div class="box">
                <img src="{% static 'images/bogdan.png' %}" alt="team member">
                <h2>Bogdan</h2>
                <p>Scrum Master</p>
                <p>
                    <a href="https://www.linkedin.com/in/bogdan-gugu-83ba4b11a/" target="_blank">
                        <i class="fa fa-linkedin fa-2x"></i>
                    </a>
                </p>
            </div>
            <div class="box">
                <img src="{% static 'images/marko.png' %}" alt="team member">
                <h2>Marko</h2>
                <p>Frontend:Authentication Design</p>
                <p>
                    <a href="https://www.linkedin.com/in/markohautala/" target="_blank">
                        <i class="fa fa-linkedin fa-2x"></i>
                    </a>
                </p>
            </div>
            <div class="box">
                <img src="{% static 'images/johnny.png' %}" alt="team member">
                <h2>Johnny</h2>
                <p>Frontend:Navigation Design</p>
                <p>
                    <a href="/" target="_blank">
                        <i class="fa fa-linkedin fa-2x"></i>
                    </a>
                </p>
            </div>
            <div class="box">
                <img src="{% static 'images/andreas.png' %}" alt="team member">
                <h2>Andreas</h2>
                <p>Documentation</p>
                <p>
                    <a href="https://www.linkedin.com/in/andreas-jelenko-03b061172/" target="_blank">
                        <i class="fa fa-linkedin fa-2x"></i>
                    </a>
                </p>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
<!-- Specific JavaScript for the Contact page can be placed here -->
<script src="https://kit.fontawesome.com/27cbf33ba8.js" crossorigin="anonymous"></script>
{% endblock %}

templates/npv/create-evaluation.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h3 class="calculator-headings">Create Evaluation</h3>
<div class="site-container calculator-container col-md-6">
    
        {% comment %} TODO: Limit discount rate {% endcomment %}
        
        <form class="site-form" action="{% url 'create_evaluation' %}" method="post">
            <h4>Evaluation Details</h3>
            {% csrf_token %}
            <div id="forms">
                {{ form.as_p }}
            </div>
            
            <button type="submit">Create Evaluation</button>
        </form>
</div>

{% endblock %}

templates/npv/edit-eval.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="title">Edit Evaluation - {{eval_name}}</div>

    <div class="col-md-5">
        <div class="form-area">
            {% comment %} TODO: Limit discount rate {% endcomment %}
            
                <form action="{% url 'edit_evaluation' evaluation_id=evaluation_id %}" method="post">
                <br style="clear:both">
                <h4 style="margin-bottom: 25px; text-align: center;">Evaluation Details</h3>
                {% csrf_token %}
                <div id="forms">
                    {{ form.as_p }}
                </div>
                
                <input type="submit" value="Save Changes">                
            </form>
        </div>
        </div>
    </div>

</div>

{% endblock %}

templates/npv/list-projects.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container mt-4">
    <h1 class="text-white">Project for Evaluation: {{evaluation_name}}</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Init. Invest. $</th>
                <th scope="col">Period</th>
                <th scope="col">NPV $</th>
                <th scope="col">Ann. NPV $</th>
                <th scope="col">Viable</th>
                <th scope="col">Rank</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for project in projects %}
            <tr>
                <td>{{ project.name }}</td>
                <td>{{ project.initial_investment }}</td>
                <td>{{ project.period }}</td>
                <td>{{ project.npv }} </td>
                <td>{{ project.annualized_npv }}</td>
                {% if project.get_consider_further_display == "Rejected" %}
                  <td><span class="cross">&#10006</span></td>
                {% else %}
                  <td><span class="check">&#10004</span></td>
                {% endif %}
                <td>{{ project.rank }}</td>
                {% if project.evaluation.user == user %}
                <td><a href="{% url 'edit_project' project_id=project.id %}">Edit</a></td>
                <td><button type="button" class="btn btn-primary delete_project" data-bs-toggle="modal" data-id="{{ project.id }}" data-bs-target="#exampleModal">
                    Delete
                  </button></td>
                {% else %}
                <td></td>
                <td></td>
                {% endif %}
            </tr>
            {% empty %}
            <tr>
                <td colspan="9">No projects have been added yet.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'add_project' evaluation_id=projects.0.evaluation.id %}" class="btn btn-primary">Add Project</a>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete this Project</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        
        <div class="modal-footer">
            <a href="" id="delete-this-proj" class="btn btn-primary">Delete</a>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          
        </div>
      </div>
    </div>
  </div>

  <script>

    $(document).on("click", ".delete_project", function () {
        var projectID = $(this).data('id');
        document.getElementById("delete-this-proj").setAttribute("href", "/delete_project/" + projectID + "/");
    });
    
</script>
{% endblock %}